FROM maven:3.5.4-jdk-8-alpine as maven
COPY ./pom.xml ./pom.xml
COPY ./src ./src
RUN mvn dependency:go-offline -B
RUN mvn package

FROM openjdk:8
WORKDIR /tmp
COPY --from=maven target/spring-boot-helloworld-0.0.1-SNAPSHOT.jar ./app.jar
EXPOSE 8080
ENTRYPOINT [ "java", "-Djava.security.egd=file:/dev/./urandom", "-Xdebug", "-jar", "/tmp/app.jar" ]
